### ISSUE TITLE
Unwanted window.close() event on Edge / IE 11

### ISSUE THREAD

**Issue by hleduff** [ReachFive/identity-web-core-sdk#124]
Hello,

I am getting an issue on a client's website I work on. Upon loading any page on the site on IE 11 and Edge =< 18, a system alert window pops up, saying:

"The webpage you are viewing is trying to close the window.
Do you want to close this window?"

From what I gather, the problem is [this one](https://stackoverflow.com/questions/38680000/why-close-warning-appears-in-microsoft-edge): a script is trying to close a window with window.close() although said window was not opened by the same script.

The only "window.close" I can find anywhere in my code is in the winchan module of ReachFive's identity-core.js, which is required by one of my scripts.
Since ReachFive is compatible with IE 11 and Edge I am confused. Maybe I am misusing one of the features. Maybe I should be raising the issue with the authors of the winchan package. 

Thanks in advance for your help.

**Comment by axuan25** [comment]
Hi @hleduff, thanks for reaching out to us for your problem, and sorry that you're having trouble with your integration.

Could you tell us a little more about your deployment and which version of identity-core you're using?

Best regards,

**Comment by hleduff** [comment]
Thanks for your reply.

I am using version 1.17.1 of identity-core. It's imported as an ES6 module in a script (which I can show you if it helps) that handles user login (through email or social providers), logout, password reset.
On document ready, on any page, this script will check if a session is active.
On any page, one button in the main menu will either redirect to a separate website (for the user account) if the user is logged in, or open a modal window if the user is not logged in. From this window they can login, ask for a password reset or click “subscribe" and be redirected to the separate website I've mentioned.
On some pages of the site there are "like" buttons: when clicked either the corresponding content will be marked as a favorite in their account if the user is logged in, or prompt the user to log in if their session isn't active.
The unwanted alert window appears on any page of the website.

The website built with Symfony 4.3.
Front-end assets are compiled with Symfony's Webpack Encore (version 0.31.0). That includes JavaScript being transpiled through Babel / CoreJS.

Not sure what is relevant and what isn't so feel free to ask for more details.

**Comment by axuan25** [comment]
Thanks for the info @hleduff.

Just wondering: is this something new that appeared in version `1.17.1` of identity-core? Would you mind telling me if this also happens in version `1.15.0`, specifically?

**Comment by hleduff** [comment]
@axuan25 spot on! Rolled back identity-core to 1.15.0 and the pop-up doesn't show.

Originally we had used 1.9.3 and never noticed the bug, so clearly something happened after 1.15.0.

Many thanks for your help!

**Comment by axuan25** [comment]
Thanks, @hleduff! In that case, I might have an idea of what is causing the issue. You mentioned that you call `checkSession` each time the page is loaded, and it could be related to a recent modification of this method.

I'll close the issue for now. In the meanwhile, don't hesitate to _Watch_ the [releases](https://github.com/ReachFive/identity-web-core-sdk/releases). We'll be patching this up shortly 😃 

Kind regards

**Comment by axuan25** [comment]
Hi @hleduff ! This issue is now resolved in version `1.17.2` ([releases](https://github.com/ReachFive/identity-web-core-sdk/releases)). You can upgrade with peace of mind 😃 Thanks for reporting it to us!
