### ISSUE TITLE
codeVerifier is required

### ISSUE THREAD

**Issue by KGALLET** [ReachFive/identity-web-core-sdk#135]
Hello, 

I just upgrade my project dep from 1.17.2 to 1.18.1 in order to get the #130 feature.
That work great. But It looks like there is a regression caused by #127. 

Everything works great if I rollback to 1.17.2.

Now with 1.18.1 when I use the loginWithSocialProvider method, the backend API returns an error (401 Unauthorized) cause he is waiting for a code_verifier in the request. 
It's really annoying since we can't use social connect on the mobile app anymore. (we stayed with 1.17.2 for now)

Is there something we need to do in our back end ? Didn't find any docs related to this in the changelog/release notes.
Do we need to pass the verifierKey that is stored in the session storage ? What's the purpose of doing that ? 

Thank's

**Comment by axuan25** [comment]
Hi @KGALLET, thanks again for reaching out to us!

This is a known issue and will be resolved thanks to #134. Test cases have also been revised so as to prevent future occurrences.

While the fix should resolve the issue to avoid such breaking changes in existing deployments, it also hints that you might be using a less secure flow for your app.

- If you are using a public identity client (auth method `none` in the console) and exchanging the auth code using your backend (therefore without a code_verifier), your flow is at high risk.
- If you are using a confidential identity client (auth method `post` or `basic`) and exchanging the auth code using your backend, you might possibly be missing out on some recommended security measures, but I would need to know more about your deployment first.

Would you be kind enough to reach out to me by email so we can discuss the specifics of your flow in private? You can reach me at `christopher [at] reach5 [dot] co`.

**Comment by KGALLET** [comment]
Hello @axuan25,

Thank's for your reply. 
As for now we will not deploy with the latest version of the library, until the fix is done by your side. So that we do not need to change the secure flow of our app. 
I'm gonna fork master then revert the undesired commit so that we will not be getting the pkce error.

We might contact you further, if needed. 

Thank's
