### ISSUE TITLE
Main inside package.json is referencing to es6 modules

### ISSUE THREAD

**Issue by lyrixx** [ReachFive/identity-web-core-sdk#3]
Hello,

In the "main" inside package.json is referencing to es6 modules (lowdash-es).
So we could not compile our JS with this lib

It's the same issue than https://github.com/material-components/material-components-web/issues/929 (for example)

Could you compile your lib to es5 only ?
Thanks

**Comment by jcdelmas** [comment]
Hello,

Thanks for the issue.
Can you try the new version 1.1.2 ?
Normally, the problem has been fixed.

**Comment by lyrixx** [comment]
Hello
Thanks for the patch. It's now fixed :+1:
