### ISSUE TITLE
Type of params for verification code sms

### ISSUE THREAD

**Issue by mathieu-morchipont** [ReachFive/identity-web-core-sdk#84]
The verification code has a params with type "PasswordlessParams"
`verifyPasswordless(params: PasswordlessParams, auth = {})`

But the expected params are "{phoneNumber:'', verificationCode:''}"

Could you create the next type and assign to verifyPasswordless params
`export type SmsVerificationCodeParams = {
  phoneNumber: string;
  verificationCode: string;
}`

Thanks

**Comment by roxanemace** [comment]
Hello, this issue was resolved with the [`v1.12.1`](https://github.com/ReachFive/identity-web-core-sdk/releases/tag/v1.12.1). Sorry for the delay!
