### ISSUE TITLE
sendEmailVerification -  doesn't work returnToAfterEmailConfirmation field

### ISSUE THREAD

**Issue by AlexanderSribnyi** [ReachFive/identity-web-core-sdk#96]
When I try to send verification email I want to use custom URL to witch I'll return after clicking on the verification link. So in method **sendEmailVerification** I use field **returnToAfterEmailConfirmation**, but in verification link query param **redirect_url** is steel default as in dashboard.

**Comment by YannTR5** [comment]
As discussed, this functionnality is available only when you use "Hosted Pages" module.
